#!/usr/bin/env python
from __future__ import print_function

import boto3
import yaml, os
import xbow

cfg_file = os.path.join(xbow.XBOW_CONFIGDIR, "settings.yml")

with open(cfg_file, 'r') as ymlfile:
    cfg = yaml.load(ymlfile)

client = boto3.client('efs')

#response = client.describe_file_systems(CreationToken=cfg['creation_token'])
response = client.describe_file_systems(CreationToken='MyTestFileSystem')

#FileSystemID = json.loads('response')

['ResponseMetadata', u'FileSystems']


FileSystemId = [s['FileSystemId'] for s in response['FileSystems']]

print(response)
print(FileSystemId)

def create_FS():
    response = client.create_file_system(
        CreationToken=cfg['creation_token'],
        PerformanceMode='generalPurpose',
        Encrypted=True,
    )

def tag_FS():
    client.create_tags(
        FileSystemId='fs-77ce46be',
        Tags=[
            {
                'Key': 'Name',
                'Value': cfg['creation_token']
            },
        ]
    )

try:
    result = create_FS()
    print(result)
except ValueError as e:
    print(e)
