#!/us:r/bin/env python
from __future__ import print_function

import boto3
import yaml, os
import xbow
from xbow import filesystems
import time

cfg_file = os.path.join(xbow.XBOW_CONFIGDIR, "settings.yml")
with open(cfg_file, 'r') as ymlfile:
    cfg = yaml.load(ymlfile)
fs_id = filesystems.create_fs(cfg['shared_file_system'], region=cfg['region'],
                              efs_security_groups=cfg['efs_security_groups'])
print('Filesystem created')
