#!/usr/bin/env python
from __future__ import print_function

import os, yaml

def create_aws():
    print('Setting up AWS Credentials\n'
	  'AWS Access Key ID: foo\n'
          'AWS Secret Access Key: bar\n'
	  'Default region name [us-west-2]: us-west-2\n'
	  'Default output format [None]: json')

def create_settings():
    """
    Create a settings configuration file for use with xbow
    """
    try:

        # Test for the old directory presence (IE updating).
        if os.path.isdir(os.path.expanduser('~/.Xbow')):

            os.rename(os.path.expanduser('~/.Xbow'),
                      os.path.expanduser('~/.xbow'))
        
	# Setting up the .xbow directory.
        if not os.path.isfile(os.path.expanduser('~/.xbow/settings.yml')):

            print('Xbow will create a hidden directory in your $HOME directory \n'
                  'in which it will create the hosts configuration file. You will\n'
                  'need to edit this file with your cloud preferences for the \n'
                  'cloud machines you wish to use. See documentation for more \n'
                  'information on best cloud practices.')

            #os.mkdir(os.path.expanduser('~/.xbow'))

            HOSTFILE = open(os.path.expanduser('~/.xbow/settings.yml'), 'w+')
	    #HOSTFILE = open(cfg_file, 'w+')

	    HOSTFILE.write('region: eu-west-1\n')
	    HOSTFILE.write("price: '0.5'\n")
	    HOSTFILE.write('worker_instance_type: m4.large\n')
	    HOSTFILE.write('scheduler_instance_type: t2.small\n')
	    HOSTFILE.write('image_id: ami-3730464e # new image created 11th Feb\n')
	    HOSTFILE.write("#ec2_security_groups: ['SG-Xbow']\n")
	    HOSTFILE.write("ec2_security_groups: ['efs-walkthrough1-ec2-sg']\n")
	    HOSTFILE.write("efs_security_groups: ['efs-walkthrough1-mt-sg']\n")
	    HOSTFILE.write('shared_file_system: MyTestFileSystem\n')
	    HOSTFILE.write('mount_point: /home/ubuntu/shared\n')
	    HOSTFILE.write('cluster_name: MyDaskCluster\n')
	    HOSTFILE.write('scheduler_name: MyDaskScheduler\n')
	    HOSTFILE.write('worker_pool_name: MyDaskWorkers\n')
	    HOSTFILE.write('pool_size: 2\n')

	    HOSTFILE.close()


        else:

            print("Settings.yml already exists at '~/.xbow, xbow is skipping "
                  "creating a new one.")

    except IOError:

        print('Xbow failed to create the host configuration file in '
              '"~/.xbow/settings.yml", you will have to do this manually. The '
              'user documentation details the information that should be in this '
              'file.')

create_aws()

try:
    result3 = create_settings()
except IOError as e:
    print(e)
