#!/usr/bin/env python
from __future__ import print_function

import boto3

# Terminates all running instances
# TO DO:
# - 'Hard' Terminate = Cancels all persistent spot requests, terminates all instances
# - 'Soft' Terminate = Cancels all persistent spot requests, only terminates workers

ec2 = boto3.client('ec2')
response = ec2.describe_instances()

for reservation in response["Reservations"]:
    for instance in reservation["Instances"]:
	instanceId = instance["InstanceId"]
	ec2.terminate_instances(InstanceIds=[instanceId], DryRun=False)


