#!/usr/bin/env python
from __future__ import print_function
from xbowflow._version import __version__

from dask.distributed import Client
from xbowflow.pipelines import SubprocessKernel, Pipeline
import sys
import os
import socket

#ip = socket.gethostbyname(socket.gethostname())
#dask_scheduler = '{}:8786'.format(ip)
#client = Client(dask_scheduler)
client = Client()
cmd = ' '.join(sys.argv[1:])

cmd = 'cd {}; {}'.format(os.getcwd(), cmd)
kernel = SubprocessKernel(cmd)
pipe = Pipeline(client, [kernel])
result = pipe.run({})
print(result['output'])
client.close()
