#!/usr/bin/env python
from __future__ import print_function
import sys
import os
import argparse
from xbowflow._version import __version__
from xbowflow.xflowlib import remote_run
from xbowflow.clients import dask_client
parser = argparse.ArgumentParser()

parser.add_argument('cmd', type=str, help='the command to submit')
parser.add_argument('-V', '--version', action='version', version=__version__)

args = parser.parse_args()
if __name__ == '__main__':
    client = dask_client()
    remote_run(client, args.cmd)
